"""Build Phase 3A synthesis artifacts from completed Phase 1/2 notes.

This script is intentionally local and deterministic. It does not call
NotebookLM or any external model. It reads the parsed registry and the
NotebookLM-backed notes already present in the repository, then writes the
Phase 3A synthesis infrastructure requested for the Fondecyt working memo.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
TODAY = dt.date.today().isoformat()

REQUIRED_SCHEMA = [
    "claim_id",
    "source_id",
    "question_id",
    "paper_key",
    "page_ref",
    "dimension",
    "concept",
    "definition",
    "mechanism",
    "causal_chain",
    "variables_parameters",
    "theory_evidence_status",
    "claim_text",
    "project_use",
    "validation_status",
    "reviewer_comment",
]

OPTIONAL_SCHEMA = [
    "note_path",
    "cluster_id",
    "cluster_question_id",
    "evidence_anchor",
    "quote_or_paraphrase",
    "memo_section_target",
    "confidence",
]

EXTRACTION_COLUMNS = REQUIRED_SCHEMA + OPTIONAL_SCHEMA

MANDATORY_CONCEPTS = [
    "land",
    "land rent",
    "housing rent",
    "real estate",
    "productive capital",
    "wealth",
    "land price",
    "fundamental value",
    "bubble",
    "land overvaluation",
    "collateral value",
    "leverage",
    "unbalanced growth",
    "R versus G",
    "debt rollover",
]

CONCEPT_ALIASES = {
    "land": ["fixed factor", "non-produced asset", "T"],
    "land rent": ["rent", "land dividend", "D_t", "R"],
    "housing rent": ["imputed rent", "housing services"],
    "real estate": ["housing", "property", "urban land"],
    "productive capital": ["capital stock", "K", "machines", "produced capital"],
    "wealth": ["W", "measured wealth", "balance-sheet wealth"],
    "land price": ["P_t", "p", "asset price"],
    "fundamental value": ["fundamentals", "present value of rents", "dividend value"],
    "bubble": ["rational bubble", "speculative bubble"],
    "land overvaluation": ["overvalued land", "Land Overvaluation Theorem"],
    "collateral value": ["collateral", "pledgeable value"],
    "leverage": ["borrowing", "loan-to-value", "credit expansion"],
    "unbalanced growth": ["structural transformation", "sectoral productivity"],
    "R versus G": ["R>G", "R<G", "return-growth gap"],
    "debt rollover": ["infinite debt rollover", "public debt rollover"],
}

CONCEPT_DEFINITIONS = {
    "land": "Non-produced, fixed or scarce asset whose productive role, store-of-value role, and collateral role must be separated.",
    "land rent": "Flow return or dividend generated by land, analytically distinct from capitalized land price and from housing rent.",
    "housing rent": "Payment or imputed service flow from housing use; it must not be collapsed into pure land rent or land price.",
    "real estate": "Composite asset category combining land and produced structures; it must not be treated as pure land or pure capital.",
    "productive capital": "Produced assets used in production, commonly represented by K, distinct from wealth and land values.",
    "wealth": "Market-valued ownership claim over resources, including productive capital plus capitalized rents and non-produced assets.",
    "land price": "Capitalized asset price of land, commonly P_t or p, which can move separately from current land rents.",
    "fundamental value": "Present value of land rents or dividends under the model's discounting structure.",
    "bubble": "Asset-price component or path not pinned down by fundamental dividend value under rational-expectations dynamics.",
    "land overvaluation": "Systematic divergence of land price above rent fundamentals generated by structural conditions, not merely irrational exuberance.",
    "collateral value": "Value of land or real estate as pledgeable security for credit creation.",
    "leverage": "Borrowing or balance-sheet amplification that links credit conditions to land-price movements.",
    "unbalanced growth": "Differential productivity growth across land-intensive and non-land sectors or factors.",
    "R versus G": "Relation between returns or interest factors and growth rates used in dynamic efficiency and debt-rollover arguments.",
    "debt rollover": "Sustainability of rolling over debt without repayment, affected by land and return-growth conditions.",
}

MANDATORY_MECHANISMS = [
    "land speculation crowds out productive capital",
    "real-estate credit amplifies land-price inflation",
    "leverage creates land-bubble phase transition",
    "unbalanced growth separates land prices from rents",
    "land changes R versus G and debt-rollover conditions",
    "land taxation/regulation redirects savings toward productive investment",
    "land/wealth measurement distinction affects interpretation of capital accumulation",
    "wobbly dynamics produces endogenous instability and bounded boom-bust paths",
]

MECHANISM_RULES = {
    "land speculation crowds out productive capital": ["speculation", "crowd", "productive capital", "investment"],
    "real-estate credit amplifies land-price inflation": ["credit", "collateral", "land price", "real estate"],
    "leverage creates land-bubble phase transition": ["leverage", "phase transition", "bubble"],
    "unbalanced growth separates land prices from rents": ["unbalanced growth", "rent", "overvaluation"],
    "land changes R versus G and debt-rollover conditions": ["debt rollover", "R", "G", "dynamic efficiency"],
    "land taxation/regulation redirects savings toward productive investment": ["tax", "regulation", "policy", "productive investment"],
    "land/wealth measurement distinction affects interpretation of capital accumulation": ["wealth", "productive capital", "measurement"],
    "wobbly dynamics produces endogenous instability and bounded boom-bust paths": ["wobbly", "instability", "bounded", "boom"],
}

VARIABLES = [
    ("P_t", "land price"),
    ("D_t or r_t", "land rent/dividend"),
    ("K_t", "capital stock"),
    ("k_{t+1}", "productive investment or next-period capital"),
    ("R", "gross return / interest-return concept when used"),
    ("r", "safe interest rate when used"),
    ("G", "growth rate"),
    ("leverage parameter", "borrowing or balance-sheet amplification"),
    ("collateral parameter", "pledgeability of land or real estate"),
    ("elasticity of substitution between land and non-land factors", "substitution parameter"),
    ("productivity growth by sector or factor", "sectoral productivity growth"),
    ("wealth W where present", "measured wealth"),
    ("productive capital versus measured wealth distinction", "capital/wealth distinction"),
]

THEMES = [
    "Definitions and conceptual separations",
    "Asset-price and wealth-measurement claims",
    "Growth and capital-formation mechanisms",
    "Credit, leverage, collateral, and monetary policy",
    "Unbalanced growth and overvaluation",
    "Debt rollover and dynamic efficiency",
    "Wobbly dynamics and endogenous instability",
    "Policy and institutional implications",
    "Critical adaptation to urban land-rent financialization in Latin America",
]

THEME_RULES = {
    THEMES[0]: ["definition", "distinguish", "wealth", "capital", "rent", "real estate"],
    THEMES[1]: ["wealth", "measurement", "asset price", "capitalized"],
    THEMES[2]: ["crowd", "investment", "capital formation", "growth", "productive capital"],
    THEMES[3]: ["credit", "collateral", "leverage", "monetary", "interest"],
    THEMES[4]: ["unbalanced growth", "overvaluation", "fundamental", "rent"],
    THEMES[5]: ["debt rollover", "R", "G", "dynamic efficiency"],
    THEMES[6]: ["wobbly", "instability", "phase transition", "boom", "bust"],
    THEMES[7]: ["policy", "tax", "regulation", "welfare"],
    THEMES[8]: ["Latin America", "Latin American", "Fondecyt", "transport", "applicability", "caveat"],
}

MEMO_SECTIONS = [
    ("1", "Introduction: why this literature matters for land rent and financialization"),
    ("2", "Method: corpus, notes, extraction protocol, screening, synthesis"),
    ("3", "Conceptual objects: land, rent, wealth, capital, real estate, bubble"),
    ("4", "Mechanism I: land-price inflation and capital-formation crowding-out"),
    ("5", "Mechanism II: credit expansion, collateral, leverage, and monetary policy"),
    ("6", "Mechanism III: unbalanced growth and the Land Overvaluation Theorem"),
    ("7", "Mechanism IV: R versus G, land, and infinite debt rollover"),
    ("8", "Wobbly dynamics and instability as supplementary branch"),
    ("9", "Critical appraisal: assumptions, scope, Latin American transportability"),
    ("10", "Research agenda: what the Fondecyt project should retain, modify, or reject"),
    ("11", "Conclusion"),
]

PARAGRAPH_FUNCTIONS = [
    "define object",
    "explain mechanism",
    "specify causal chain",
    "distinguish variables",
    "state theorem/model result",
    "appraise evidence",
    "translate to Fondecyt",
    "identify limitation",
    "transition",
]


def rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in columns})


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    fm_text = parts[1]
    body = parts[2]
    fm: dict[str, str] = {}
    for line in fm_text.splitlines():
        if ":" not in line or line.strip().startswith("#"):
            continue
        key, value = line.split(":", 1)
        value = value.strip().strip('"').strip("'")
        fm[key.strip()] = value
    return fm, body


def section(text: str, heading: str) -> str:
    pattern = re.compile(rf"^##\s+{re.escape(heading)}\s*$", re.MULTILINE)
    match = pattern.search(text)
    if not match:
        return ""
    start = match.end()
    next_match = re.search(r"^##\s+", text[start:], flags=re.MULTILINE)
    end = start + next_match.start() if next_match else len(text)
    return text[start:end].strip()


def first_sentence(text: str, max_len: int = 700) -> str:
    cleaned = re.sub(r"\s+", " ", strip_markdown(text)).strip()
    cleaned = cleaned.strip("- ")
    if not cleaned:
        return ""
    split = re.split(r"(?<=[.!?])\s+", cleaned)
    sentence = split[0] if split else cleaned
    if len(sentence) > max_len:
        sentence = sentence[:max_len].rsplit(" ", 1)[0] + "..."
    return sentence


def strip_markdown(text: str) -> str:
    text = re.sub(r"\[\[([^\]]+)\]\]", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[*_`>#]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def bullet_value(text: str, label: str) -> str:
    pattern = re.compile(rf"^-\s+\*\*{re.escape(label)}\*\*:\s*(.*)$", re.MULTILINE)
    match = pattern.search(text)
    return match.group(1).strip() if match else ""


def mechanism_bullets(distilled: str) -> list[str]:
    lines = distilled.splitlines()
    bullets: list[str] = []
    in_mechanism = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- **Mechanism**"):
            in_mechanism = True
            continue
        if in_mechanism and stripped.startswith("- **"):
            break
        if in_mechanism and stripped.startswith("- "):
            bullets.append(stripped[2:].strip())
    return bullets


def page_ref(evidence: str) -> str:
    match = re.search(r"Page\(s\):\s*([^\n]+)", evidence, flags=re.IGNORECASE)
    if not match:
        return ""
    value = match.group(1).strip()
    if "unknown" in value.lower() or "page_unknown" in value.lower():
        return ""
    return value


def evidence_anchor(evidence: str) -> str:
    lines = [line.strip() for line in evidence.splitlines() if line.strip()]
    return " ".join(lines[:3])[:900]


def concept_for(text: str) -> str:
    low = text.lower()
    for concept, aliases in CONCEPT_ALIASES.items():
        candidates = [concept] + aliases
        for candidate in candidates:
            if candidate.lower() in low:
                return concept
    return "land"


def dimension_for(text: str, tag: str = "") -> str:
    low = f"{tag} {text}".lower()
    if any(word in low for word in ["definition", "difference", "distinguish", "concept"]):
        return "definition"
    if any(word in low for word in ["condition", "causal", "chain", "affect", "because"]):
        return "causality"
    if any(word in low for word in ["p_t", "k_t", "r ", " r.", " g", "sigma", "elasticity", "parameter", "variable", "$"]):
        return "variables_parameters"
    if any(word in low for word in ["evidence", "empirical", "measurement", "theorem", "formal", "model"]):
        return "theory_evidence"
    return "mechanism"


def mechanism_for(text: str) -> str:
    low = text.lower()
    for mechanism, words in MECHANISM_RULES.items():
        if any(word.lower() in low for word in words):
            return mechanism
    return ""


def variables_for(text: str) -> str:
    found = []
    low = text.lower()
    rules = [
        ("P_t", ["p_t", "price of land", "land price", " p "]),
        ("D_t/r_t", ["rent", "dividend"]),
        ("K_t", ["capital stock", "productive capital", " k "]),
        ("k_{t+1}", ["next-period capital", "investment"]),
        ("R", ["gross return", " r versus g", "r versus g", "r>g", "r<g"]),
        ("r", ["interest rate", "safe rate", "discount"]),
        ("G", ["growth rate", " g "]),
        ("leverage parameter", ["leverage", "borrowing"]),
        ("collateral parameter", ["collateral", "pledge"]),
        ("elasticity of substitution", ["elasticity", "sigma", "substitution"]),
        ("productivity growth", ["productivity", "unbalanced growth"]),
        ("W", ["wealth", " w "]),
    ]
    for symbol, words in rules:
        if any(word in low for word in words):
            found.append(symbol)
    return "; ".join(dict.fromkeys(found))


def theory_status(text: str, tag: str = "") -> str:
    low = f"{tag} {text}".lower()
    if "theorem" in low or "formal" in low:
        return "formal_model_result"
    if "empirical" in low or "measurement" in low or "evidence" in low:
        return "measurement_or_empirical_motivation"
    if "policy" in low or "tax" in low or "regulation" in low:
        return "policy_implication"
    if "caveat" in low or "latin" in low or "transport" in low:
        return "critical_interpretation"
    return "model_based_synthesis"


def project_use(text: str) -> str:
    low = text.lower()
    if "overvaluation" in low or "unbalanced" in low:
        return "land overvaluation theorem"
    if "credit" in low or "collateral" in low or "leverage" in low:
        return "land-credit crowding-out"
    if "debt" in low or "r versus g" in low or "r>g" in low or "r<g" in low:
        return "debt rollover / R versus G"
    if "wobbly" in low or "instability" in low or "phase transition" in low:
        return "wobbly dynamics and instability"
    if "policy" in low or "tax" in low or "regulation" in low:
        return "policy / taxation / regulation"
    if "latin" in low or "fondecyt" in low:
        return "Latin American applicability"
    return "land-credit crowding-out"


def validation_for(page: str, text: str) -> str:
    low = text.lower()
    if "not supported" in low:
        return "not_supported"
    if "outside scope" in low:
        return "outside_scope"
    if page:
        return "validated_paraphrase"
    return "needs_page"


def make_claim(
    note_id: str,
    seq: int,
    text: str,
    source_id: str,
    question_id: str,
    paper_key: str,
    page: str,
    note_path: Path,
    cluster_id: str = "",
    cluster_question_id: str = "",
    tag: str = "",
    anchor: str = "",
    comment: str = "",
) -> dict[str, str]:
    clean = first_sentence(text)
    dimension = dimension_for(clean, tag)
    concept = concept_for(clean)
    mechanism = mechanism_for(clean)
    return {
        "claim_id": f"CLM_{note_id}_{seq:03d}",
        "source_id": source_id,
        "question_id": question_id,
        "paper_key": paper_key,
        "page_ref": page,
        "dimension": dimension,
        "concept": concept,
        "definition": clean if dimension == "definition" else "",
        "mechanism": mechanism,
        "causal_chain": clean if dimension in {"causality", "mechanism"} else "",
        "variables_parameters": variables_for(clean),
        "theory_evidence_status": theory_status(clean, tag),
        "claim_text": clean,
        "project_use": project_use(clean),
        "validation_status": validation_for(page, clean),
        "reviewer_comment": comment or ("Needs precise page verification before memo drafting." if not page else "NotebookLM-backed paraphrase from completed note; verify exact wording before final quotation."),
        "note_path": rel(note_path),
        "cluster_id": cluster_id,
        "cluster_question_id": cluster_question_id,
        "evidence_anchor": anchor,
        "quote_or_paraphrase": "paraphrase",
        "memo_section_target": memo_target(clean),
        "confidence": "medium" if page else "low",
    }


def memo_target(text: str) -> str:
    low = text.lower()
    if "wealth" in low or "definition" in low or "capital" in low:
        return "3. Conceptual objects"
    if "crowd" in low or "investment" in low:
        return "4. Mechanism I"
    if "credit" in low or "collateral" in low or "leverage" in low:
        return "5. Mechanism II"
    if "unbalanced" in low or "overvaluation" in low:
        return "6. Mechanism III"
    if "debt" in low or "r versus g" in low or "dynamic efficiency" in low:
        return "7. Mechanism IV"
    if "wobbly" in low or "instability" in low:
        return "8. Wobbly dynamics"
    if "latin" in low or "caveat" in low or "applicability" in low:
        return "9. Critical appraisal"
    if "policy" in low or "tax" in low or "regulation" in low:
        return "10. Research agenda"
    return "1. Introduction"


def resolve_note_dirs() -> tuple[Path, Path, list[str]]:
    notes_root = ROOT / "03_notes"
    questions = notes_root / "questions"
    clusters = notes_root / "clusters"
    notes = []
    if questions.exists() and clusters.exists():
        notes.append("Using canonical Phase 3A note paths: 03_notes/questions and 03_notes/clusters.")
        return questions, clusters, notes
    fallback_q = ROOT / "notes" / "questions"
    fallback_c = ROOT / "notes" / "clusters"
    if fallback_q.exists() and fallback_c.exists():
        notes.append("Canonical 03_notes paths were absent; using fallback notes/questions and notes/clusters.")
        return fallback_q, fallback_c, notes
    raise FileNotFoundError("Could not find either 03_notes/{questions,clusters} or notes/{questions,clusters}.")


def build_skill(path: Path) -> None:
    text = f"""# Phase 3 Land-Rent Synthesis Skill

## Review Type

Theory-led systematic narrative review.

## Governing Review Question

How does the Hirano-Stiglitz-Toda branch explain the relation between land-price inflation, credit expansion, unbalanced growth, capital formation, land overvaluation, and debt rollover, and how can that reconstruction be translated cautiously to Latin American land-rent financialization contexts?

## Six Subquestions

1. How does land-price inflation affect productive capital formation and growth?
2. How do private credit expansion, real-estate credit, and collateral financing amplify land-price inflation?
3. What do the Land Overvaluation Theorem and unbalanced growth explain?
4. How does land speculation alter R versus G and infinite debt rollover conditions?
5. How must land, housing, real estate, productive capital, wealth, rents, and bubbles be distinguished?
6. Which assumptions travel, fail to travel, or require empirical validation for Latin American urban land-rent financialization cases?

## Included Corpus Boundaries

- The 14-source SHT/Hirano-Stiglitz-Toda corpus registered in `02_LitRev_Sistematica/config/registry_parsed.json`.
- NotebookLM-backed Phase 1 per-paper notes and Phase 2 cluster notes.
- Land as fixed or non-produced factor, store of value, collateral object, and rent-generating asset.
- Land price, land rent, land overvaluation, bubbles, credit, collateral, leverage, unbalanced growth, wealth-capital distinction, R versus G, debt rollover, wobbly dynamics, and policy implications inside this corpus.

## Excluded and Quarantine Boundaries

- Do not import generic financialization, urban economics, housing studies, Marxian rent theory, generic OLG theory, or asset-pricing literature before reconstructing the SHT branch on its own terms.
- External literatures may later enter only as controlled comparators after Phase 3A.
- Claims without note support remain quarantined and cannot enter memo drafting.

## Source ID Convention

- Per-paper sources use `PDF001` through `PDF014`.
- Per-paper questions use `PDFXXX_QYY`.
- Cluster questions use `C#_Q##`.
- C6 is corpus-level synthesis. It must be marked as all-source inference and not treated as a normal bounded cluster.

## Extraction Dimensions

Use exactly one primary dimension per extracted claim:

- `definition`
- `mechanism`
- `causality`
- `variables_parameters`
- `theory_evidence`

## One-Row-Per-Claim Rule

Each row in the extraction matrix must represent one claim, not one paper and not one note. Split cluster-level claims into source-level claims where evidence anchors permit. If a cluster synthesis cannot be traced to one source, use `source_id=MULTI` and list related sources in `reviewer_comment`.

## Validation Categories

- `validated_exact`: exact source wording and page anchor are available.
- `validated_paraphrase`: source-grounded paraphrase and page anchor are available.
- `needs_page`: grounded in a note but lacking precise page reference.
- `unclear`: parser or reviewer cannot isolate a defensible claim.
- `not_supported`: claim is not supported by the note base.
- `outside_scope`: claim belongs outside the bounded SHT reconstruction.

## Concept Dictionary Rules

Every concept entry must include preferred term, alternatives, definition, source papers, page references or `needs_page`, distinctions from neighboring concepts, project relevance, and a Latin American transportability note.

Mandatory distinctions: land rent, housing rent, land price, real estate value, wealth, and productive capital must never be conflated.

## Mechanism Ledger Rules

Each mechanism entry must include source papers, starting condition, transmission channel, endpoint, variables/parameters, assumptions, theoretical status, policy implication, Fondecyt translation risk, source note links, and validation status.

## Thematic Synthesis Rules

Synthesis must be built from extracted claims. Cluster notes are evidence infrastructure, not final prose. The synthesis map should preserve a reconstruction-before-critique sequence.

## Fondecyt Transportability Rules

For Latin American urban land-rent and financialization cases, mark whether a claim is directly usable, requires institutional translation, requires empirical validation, depends on advanced-economy assumptions, or identifies a missing link.

## Anti-Scope Rules

- Do not draft from unsupported claims.
- Do not treat cluster notes as final memo prose.
- Do not treat C6 as a normal bounded cluster.
- Do not import external literature during Phase 3A.
- Do not fabricate page references.

## Paragraph Quality Gates

Any paragraph later entering the memo must have one primary function, explicit claim IDs, source IDs, note IDs, concepts, mechanisms, variables/parameters where relevant, validation status, and a concept-conflation risk check. Paragraphs using `not_supported`, `outside_scope`, or `unclear` claims are not draft-ready.

Generated: {TODAY}
"""
    write_text(path, text)


def build_protocol(path: Path, q_dir: Path, c_dir: Path) -> None:
    text = f"""# Phase 3A Synthesis Protocol

Generated: {TODAY}

## Purpose

Phase 3A converts completed NotebookLM-backed Phase 1 and Phase 2 notes into systematic synthesis infrastructure for a later Fondecyt working memo. It does not fetch new NotebookLM answers and does not draft the final memo.

## Governing Protocol

`05_skills/SYSTEMATIC_REVIEW_ORCHESTRATOR.md` governs the review logic. `05_skills/SKILL_SYSTEMATIC_REVIEW_LANDRENT.md` supplies the operational checklist. `05_skills/review_matrix_schema.csv` supplies the hard extraction schema. `05_skills/codex_prompt_bootstrap.md` is treated as a legacy bootstrap artifact only.

## Note Paths

- Per-paper notes: `{rel(q_dir)}`
- Cluster notes: `{rel(c_dir)}`
- Registry: `02_LitRev_Sistematica/config/registry_parsed.json`
- Cluster evidence map: `02_LitRev_Sistematica/derived/cluster_evidence_map.json`

The repository has migrated from earlier `notes/...` paths to `03_notes/...`; Phase 3A uses `03_notes/...` as canonical.

## Extraction Rule

The extraction unit is one claim. Per-paper notes supply source-level claims. Cluster notes supply synthesis claims and source-specific evidence map claims where available. Claims without page references are marked `needs_page`.

## Validation Categories

`validated_exact`, `validated_paraphrase`, `needs_page`, `unclear`, `not_supported`, `outside_scope`.

## C6 Handling

C6 is corpus-level synthesis and must be interpreted as all-source inference. It is not a normal bounded cluster.

## No-Fetch / No-Draft Boundary

This phase only builds review infrastructure. It does not call NotebookLM, does not replace NotebookLM with another model, does not import external literature, and does not draft final memo prose.
"""
    write_text(path, text)


def registry_rows(registry: dict[str, Any], q_dir: Path, c_dir: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    source_rows = []
    for paper in registry["papers"]:
        note_count = len(list(q_dir.glob(f"{paper['source_id']}_Q*.md")))
        source_rows.append({
            "source_id": paper.get("source_id", ""),
            "citation_key": paper.get("citation_key", ""),
            "authors": paper.get("authors", ""),
            "year": paper.get("year", ""),
            "title": paper.get("title", ""),
            "cluster_id": paper.get("cluster_id", ""),
            "priority": paper.get("priority", ""),
            "core_object": paper.get("core_object", ""),
            "main_mechanism": paper.get("main_mechanism", ""),
            "project_role": paper.get("project_role", ""),
            "phase1_note_count": note_count,
        })

    question_rows = []
    for q in registry["questions"]:
        note_path = q_dir / f"{q['question_id']}.md"
        question_rows.append({
            "question_id": q.get("question_id", ""),
            "source_id": q.get("source_id", ""),
            "cluster_id": q.get("cluster_id", ""),
            "tag": q.get("tag", ""),
            "status": q.get("status", ""),
            "paper_title": q.get("paper_title", ""),
            "question_text": q.get("question_text", ""),
            "note_exists": str(note_path.exists()).lower(),
            "note_path": rel(note_path) if note_path.exists() else "",
        })

    cluster_question_rows = []
    for cq in registry["cluster_questions"]:
        note_path = c_dir / f"{cq['cluster_question_id']}.md"
        cluster_question_rows.append({
            "cluster_id": cq.get("cluster_id", ""),
            "cluster_name": cq.get("cluster_name", ""),
            "cluster_question_id": cq.get("cluster_question_id", cq.get("question_id", "")),
            "question_id": cq.get("question_id", ""),
            "question_text": cq.get("question_text", ""),
            "expected_answer_type": cq.get("expected_answer_type", ""),
            "status": cq.get("status", ""),
            "related_source_ids": "; ".join(cq.get("related_source_ids", [])),
            "related_paper_titles": "; ".join(cq.get("related_paper_titles", [])),
            "note_exists": str(note_path.exists()).lower(),
            "note_path": rel(note_path) if note_path.exists() else "",
        })
    return source_rows, question_rows, cluster_question_rows


def build_question_claims(q_dir: Path, registry: dict[str, Any], papers_by_id: dict[str, dict[str, Any]]) -> list[dict[str, str]]:
    claims: list[dict[str, str]] = []
    for note_path in sorted(q_dir.glob("PDF*_Q*.md")):
        text = note_path.read_text(encoding="utf-8")
        fm, body = split_frontmatter(text)
        note_id = fm.get("note_id") or note_path.stem
        source_id = fm.get("source_id", "")
        paper = papers_by_id.get(source_id, {})
        paper_key = paper.get("citation_key", "")
        question_id = fm.get("question_id", note_id)
        cluster_id = fm.get("cluster_id", paper.get("cluster_id", ""))
        tag = fm.get("question_tag", "")
        distilled = section(body, "Distilled note")
        evidence = section(body, "Evidence / page anchors")
        page = page_ref(evidence)
        anchor = evidence_anchor(evidence)
        seq = 1
        entries = [
            bullet_value(distilled, "Core claim"),
            bullet_value(distilled, "Formal object/result, if any"),
            bullet_value(distilled, "Critical caveat"),
        ]
        entries.extend(mechanism_bullets(distilled))
        seen = set()
        for entry in entries:
            if not entry or entry.lower() in {"none", "not applicable", "n/a"}:
                continue
            clean_key = strip_markdown(entry).lower()
            if clean_key in seen:
                continue
            seen.add(clean_key)
            claims.append(make_claim(
                note_id=note_id,
                seq=seq,
                text=entry,
                source_id=source_id,
                question_id=question_id,
                paper_key=paper_key,
                page=page,
                note_path=note_path,
                cluster_id=cluster_id,
                tag=tag,
                anchor=anchor,
            ))
            seq += 1
    return claims


def parse_table_rows(table_section: str) -> list[list[str]]:
    rows = []
    for line in table_section.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or "---" in stripped:
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if cells and cells[0] == "Source ID":
            continue
        if len(cells) >= 5:
            rows.append(cells[:5])
    return rows


def build_cluster_claims(c_dir: Path, registry: dict[str, Any], papers_by_id: dict[str, dict[str, Any]]) -> list[dict[str, str]]:
    claims: list[dict[str, str]] = []
    for note_path in sorted(c_dir.glob("C*_Q*.md")):
        text = note_path.read_text(encoding="utf-8")
        fm, body = split_frontmatter(text)
        note_id = fm.get("cluster_question_id") or note_path.stem
        cluster_id = fm.get("cluster_id", "")
        question_id = fm.get("question_id", note_id)
        related_sources = fm.get("related_source_ids", "")
        notebook = section(body, "NotebookLM answer")
        notebook = notebook.replace("[NOTEBOOKLM_CLUSTER]", "").strip()
        first = first_sentence(notebook)
        seq = 1
        if first:
            claims.append(make_claim(
                note_id=note_id,
                seq=seq,
                text=first,
                source_id="MULTI",
                question_id=question_id,
                paper_key="cluster_synthesis",
                page="",
                note_path=note_path,
                cluster_id=cluster_id,
                cluster_question_id=note_id,
                tag="cluster synthesis",
                anchor="[NOTEBOOKLM_CLUSTER]",
                comment=f"Cluster-level synthesis. Related sources: {related_sources}. C6 all-source inference applies if cluster_id is C6.",
            ))
            seq += 1
        evidence_map = section(body, "Cross-paper evidence map")
        for source_id, paper_title, claim_text, evidence_text, _relevance in parse_table_rows(evidence_map):
            source_id = strip_markdown(source_id)
            page = page_ref(evidence_text)
            paper_key = papers_by_id.get(source_id, {}).get("citation_key", "")
            claims.append(make_claim(
                note_id=note_id,
                seq=seq,
                text=claim_text,
                source_id=source_id,
                question_id=question_id,
                paper_key=paper_key,
                page=page,
                note_path=note_path,
                cluster_id=cluster_id,
                cluster_question_id=note_id,
                tag="cluster evidence map",
                anchor=evidence_text[:900],
                comment=f"Source-specific row parsed from Phase 2 cluster evidence map for {paper_title}.",
            ))
            seq += 1
    return claims


def select_claims(claims: list[dict[str, str]], keywords: list[str], limit: int = 8) -> list[dict[str, str]]:
    scored = []
    for claim in claims:
        hay = " ".join([claim.get("claim_text", ""), claim.get("concept", ""), claim.get("mechanism", ""), claim.get("project_use", "")]).lower()
        score = sum(1 for word in keywords if word.lower() in hay)
        if score:
            scored.append((score, claim))
    scored.sort(key=lambda x: (-x[0], x[1]["claim_id"]))
    return [claim for _, claim in scored[:limit]]


def claim_refs(selected: list[dict[str, str]]) -> dict[str, str]:
    return {
        "claim_ids": "; ".join(c["claim_id"] for c in selected),
        "source_ids": "; ".join(dict.fromkeys(c["source_id"] for c in selected if c["source_id"])),
        "note_ids": "; ".join(dict.fromkeys(Path(c["note_path"]).stem for c in selected if c["note_path"])),
        "concepts": "; ".join(dict.fromkeys(c["concept"] for c in selected if c["concept"])),
        "mechanisms": "; ".join(dict.fromkeys(c["mechanism"] for c in selected if c["mechanism"])),
        "variables_parameters": "; ".join(dict.fromkeys(c["variables_parameters"] for c in selected if c["variables_parameters"])),
        "validation_status": "; ".join(dict.fromkeys(c["validation_status"] for c in selected if c["validation_status"])),
    }


def build_concept_dictionary(path: Path, claims: list[dict[str, str]]) -> None:
    parts = [f"# Concept Dictionary\n\nGenerated: {TODAY}\n"]
    for concept in MANDATORY_CONCEPTS:
        keywords = [concept] + CONCEPT_ALIASES.get(concept, [])
        selected = select_claims(claims, keywords, limit=10)
        refs = claim_refs(selected)
        pages = "; ".join(dict.fromkeys(c["page_ref"] for c in selected if c["page_ref"])) or "needs_page"
        sources = refs["source_ids"] or "needs_source_specific_mapping"
        note_links = ", ".join(f"[[{Path(c['note_path']).stem}]]" for c in selected[:8]) or "needs_note_mapping"
        parts.append(f"""## {concept}

- Preferred term: {concept}
- Alternative terms: {', '.join(CONCEPT_ALIASES.get(concept, [])) or 'None registered'}
- Definition: {CONCEPT_DEFINITIONS[concept]}
- Source papers: {sources}
- Page references: {pages}
- Distinction from neighboring concepts: This term must be kept analytically separate from land rent, housing rent, land price, real estate value, wealth, and productive capital unless a source explicitly links them.
- Project relevance: {project_use(' '.join(c['claim_text'] for c in selected)) if selected else 'Conceptual control for the Fondecyt memo.'}
- Transportability note: For Latin American urban land-rent and financialization cases, use this concept only after checking whether the corpus assumption maps to local tenure, credit, informality, housing, and policy institutions.
- Source note links: {note_links}
- Claim IDs: {refs['claim_ids'] or 'needs_claim_link'}
- Validation status: {refs['validation_status'] or 'needs_page'}
""")
    write_text(path, "\n".join(parts))


def build_mechanism_ledger(path: Path, claims: list[dict[str, str]]) -> None:
    parts = [f"# Mechanism Ledger\n\nGenerated: {TODAY}\n"]
    for mechanism in MANDATORY_MECHANISMS:
        selected = select_claims(claims, MECHANISM_RULES[mechanism], limit=10)
        refs = claim_refs(selected)
        note_links = ", ".join(f"[[{Path(c['note_path']).stem}]]" for c in selected[:10]) or "needs_note_mapping"
        variables = refs["variables_parameters"] or variables_for(mechanism) or "needs_variable_mapping"
        parts.append(f"""## {mechanism}

- Mechanism name: {mechanism}
- Source papers: {refs['source_ids'] or 'needs_source_mapping'}
- Starting condition: {first_sentence(selected[0]['claim_text']) if selected else 'needs_claim_support'}
- Transmission channel: {refs['mechanisms'] or 'mechanism inferred from linked claims; verify before memo drafting'}
- Endpoint: {project_use(mechanism)}
- Variables and parameters: {variables}
- Assumptions: Model assumptions must be reconstructed from linked source notes before final prose.
- Theoretical status: {refs['validation_status'] or 'needs_page'}
- Policy implication: Use only if linked claims include policy/tax/regulation support; otherwise keep as research implication.
- Fondecyt translation risk: Requires institutional translation for Latin American land, credit, housing, informality, and regulatory contexts.
- Source note links: {note_links}
- Claim IDs: {refs['claim_ids'] or 'needs_claim_link'}
- Validation status: {refs['validation_status'] or 'needs_page'}
""")
    write_text(path, "\n".join(parts))


def build_variable_ledger(path: Path, claims: list[dict[str, str]]) -> None:
    parts = [f"# Variable and Parameter Ledger\n\nGenerated: {TODAY}\n"]
    for symbol, meaning in VARIABLES:
        selected = select_claims(claims, [symbol, meaning], limit=8)
        refs = claim_refs(selected)
        parts.append(f"""## {symbol}

- Symbol: {symbol}
- Verbal meaning: {meaning}
- Source usage: {refs['source_ids'] or 'needs_source_mapping'}
- Endogenous or exogenous status: Determine source-by-source; do not generalize across models without checking the linked claims.
- Mechanism role: {refs['mechanisms'] or project_use(meaning)}
- Empirical mapping risk: Latin American applications may require proxy construction and institutional translation before empirical use.
- Neighboring concepts it must not be conflated with: land rent, housing rent, land price, real estate price, measured wealth, productive capital.
- Claim IDs: {refs['claim_ids'] or 'needs_claim_link'}
- Validation status: {refs['validation_status'] or 'needs_page'}
""")
    write_text(path, "\n".join(parts))


def build_thematic_map(path: Path, claims: list[dict[str, str]]) -> None:
    parts = [f"# Thematic Synthesis Map\n\nGenerated: {TODAY}\n\nThis map uses extracted claims rather than paper summaries.\n"]
    for i, theme in enumerate(THEMES, start=1):
        selected = select_claims(claims, THEME_RULES[theme], limit=12)
        refs = claim_refs(selected)
        core = selected[0]["claim_text"] if selected else "needs_claim_support"
        parts.append(f"""## {i}. {theme}

- Core claim: {core}
- Supporting source IDs: {refs['source_ids'] or 'needs_source_mapping'}
- Supporting note IDs: {refs['note_ids'] or 'needs_note_mapping'}
- Key mechanisms: {refs['mechanisms'] or 'needs_mechanism_mapping'}
- Variables/parameters: {refs['variables_parameters'] or 'needs_variable_mapping'}
- Theory/evidence status: {refs['validation_status'] or 'needs_page'}
- Unresolved tensions: Source assumptions, page precision, and Latin American institutional translation must be checked before memo prose.
- Memo section target: {memo_target(theme)}
- Extraction claim IDs: {refs['claim_ids'] or 'needs_claim_link'}
""")
    write_text(path, "\n".join(parts))


def build_claim_cluster_table(path: Path, claims: list[dict[str, str]]) -> None:
    rows = []
    for claim in claims:
        assigned = False
        for theme in THEMES:
            hay = " ".join([claim["claim_text"], claim["concept"], claim["mechanism"], claim["project_use"]]).lower()
            if any(word.lower() in hay for word in THEME_RULES[theme]):
                rows.append({
                    "claim_id": claim["claim_id"],
                    "synthesis_cluster": theme,
                    "source_id": claim["source_id"],
                    "note_id": Path(claim["note_path"]).stem,
                    "dimension": claim["dimension"],
                    "validation_status": claim["validation_status"],
                    "memo_section_target": claim["memo_section_target"],
                })
                assigned = True
        if not assigned:
            rows.append({
                "claim_id": claim["claim_id"],
                "synthesis_cluster": "Definitions and conceptual separations",
                "source_id": claim["source_id"],
                "note_id": Path(claim["note_path"]).stem,
                "dimension": claim["dimension"],
                "validation_status": claim["validation_status"],
                "memo_section_target": claim["memo_section_target"],
            })
    write_csv(path, rows, ["claim_id", "synthesis_cluster", "source_id", "note_id", "dimension", "validation_status", "memo_section_target"])


def build_gap_memo(path: Path, claims: list[dict[str, str]]) -> None:
    selected_latin = select_claims(claims, ["Latin", "Fondecyt", "applicability", "caveat", "transport"], limit=12)
    refs = claim_refs(selected_latin)
    text = f"""# Gap and Transportability Memo

Generated: {TODAY}

## Directly Usable Theoretical Mechanisms

The corpus directly supports mechanisms around land overvaluation, wealth-capital measurement, credit/collateral amplification, wobbly dynamics, and debt rollover. These are usable as theoretical mechanisms, not as direct empirical claims about Latin America.

## Mechanisms Requiring Institutional Translation

Land-credit and real-estate collateral mechanisms require translation into local banking rules, tenure regimes, mortgage depth, informal housing markets, fiscal structures, and urban planning institutions.

## Claims Dependent on Advanced-Economy Assumptions

Claims grounded in advanced-economy wealth measurement, deep mortgage markets, or formal land markets must be treated as conditional. They cannot be transferred as-is to Latin American land-rent financialization cases.

## Claims Requiring Empirical Validation in Latin America

Any claim about magnitude, incidence, class distribution, urban land channels, or policy effects requires regional empirical validation. Page-specific theoretical support is not enough for empirical claims.

## Missing Links to Urban Land-Rent Financialization

The SHT corpus gives a strong theoretical reconstruction of land, credit, wealth, and dynamic inefficiency. It does not by itself supply a complete account of Latin American urban informality, zoning, municipal finance, peripheral expansion, dollarization, foreign capital, or social housing finance.

## Controlled Comparator Slots for Later External Literature

External literatures may later enter only as comparators for urban land rent, housing financialization, Latin American planning institutions, informality, and empirical credit/land-price dynamics.

## Linked Transportability Claims

- Source IDs: {refs['source_ids'] or 'needs_source_mapping'}
- Note IDs: {refs['note_ids'] or 'needs_note_mapping'}
- Claim IDs: {refs['claim_ids'] or 'needs_claim_link'}
- Validation status: {refs['validation_status'] or 'needs_page'}
"""
    write_text(path, text)


def paragraph_blueprint() -> list[tuple[str, str, str, list[str], str]]:
    return [
        ("1", "define object", "State why land-rent financialization requires separating land, rent, price, wealth, credit, and productive capital.", ["land", "wealth", "productive capital"], "risk of conflating wealth with capital"),
        ("1", "transition", "Introduce the SHT branch as a bounded theory corpus for the memo.", ["SHT", "Hirano", "Stiglitz", "Toda"], "risk of importing external literatures too early"),
        ("2", "appraise evidence", "Describe the corpus, note layers, extraction protocol, and validation statuses.", ["NotebookLM", "extraction", "validation"], "risk of treating notes as final prose"),
        ("2", "transition", "Explain the reconstruction-before-critique sequence.", ["method", "reconstruction", "critique"], "risk of premature Latin American critique"),
        ("3", "define object", "Define land, land rent, housing rent, real estate, wealth, productive capital, land price, and bubble.", ["definition", "wealth", "capital", "rent"], "high concept conflation risk"),
        ("3", "distinguish variables", "Separate W, K, P_t, rents/dividends, R, r, and G.", ["W", "K", "P_t", "R", "G"], "symbol ambiguity across papers"),
        ("4", "explain mechanism", "Explain how land speculation and land-price inflation can crowd out productive investment.", ["crowd", "investment", "productive capital"], "risk of overgeneralizing model result"),
        ("4", "specify causal chain", "Specify the savings, asset-price, and capital-formation chain.", ["savings", "land price", "capital formation"], "needs source-specific page support"),
        ("5", "explain mechanism", "Explain credit, collateral, leverage, and monetary channels in land-price inflation.", ["credit", "collateral", "leverage"], "risk of treating all credit as mortgage credit"),
        ("5", "specify causal chain", "Map real-estate credit amplification into land-price and wealth effects.", ["real estate", "credit", "wealth"], "risk of conflating real estate with land"),
        ("6", "state theorem/model result", "State the Land Overvaluation Theorem and its unbalanced-growth conditions.", ["Land Overvaluation Theorem", "unbalanced growth", "elasticity"], "needs exact theorem statement before final prose"),
        ("6", "specify causal chain", "Explain why land prices can separate from rents under unbalanced growth.", ["land price", "rent", "fundamental value"], "risk of treating overvaluation as irrational bubble"),
        ("7", "state theorem/model result", "Explain how land affects R versus G and debt-rollover conditions.", ["debt rollover", "R", "G"], "symbol meanings must be source-specific"),
        ("7", "explain mechanism", "Connect land speculation and rollover capacity to dynamic efficiency.", ["dynamic efficiency", "land", "debt"], "risk of policy overreach"),
        ("8", "explain mechanism", "Present wobbly dynamics as supplementary endogenous instability branch.", ["wobbly", "instability", "bounded"], "risk of making it the main framework"),
        ("8", "specify causal chain", "Explain phase transitions, leverage, and boom-bust paths where supported.", ["phase transition", "leverage", "boom"], "needs page precision"),
        ("9", "identify limitation", "List assumptions that do not automatically travel to Latin America.", ["Latin America", "assumption", "transport"], "translation risk"),
        ("9", "translate to Fondecyt", "Identify which mechanisms can be adapted to Latin American land-rent financialization.", ["Fondecyt", "Latin American", "urban"], "do not import external literature yet"),
        ("10", "translate to Fondecyt", "State what the project should retain, modify, or reject from the SHT branch.", ["retain", "modify", "reject"], "requires supported claims only"),
        ("10", "identify limitation", "Define later comparator slots for external literature.", ["external literature", "comparators"], "must remain future-facing"),
        ("11", "transition", "Conclude the architecture without drafting final memo prose.", ["conclusion", "architecture"], "avoid final prose"),
    ]


def build_paragraph_artifacts(outline_path: Path, csv_path: Path, claims: list[dict[str, str]]) -> None:
    rows = []
    parts = [f"# Detailed Memo Outline\n\nGenerated: {TODAY}\n\nThis is paragraph architecture, not final memo prose.\n"]
    section_titles = dict(MEMO_SECTIONS)
    for idx, (section_num, function, core, keywords, risk) in enumerate(paragraph_blueprint(), start=1):
        paragraph_id = f"P{idx:02d}"
        selected = select_claims(claims, keywords, limit=6)
        refs = claim_refs(selected)
        validation = refs["validation_status"] or "needs_page"
        draft_ready = "true" if selected and all(c["validation_status"] in {"validated_exact", "validated_paraphrase"} for c in selected) else "false"
        row = {
            "paragraph_id": paragraph_id,
            "section": section_titles[section_num],
            "paragraph_function": function,
            "core_claim": core,
            "source_ids": refs["source_ids"],
            "note_ids": refs["note_ids"],
            "claim_ids": refs["claim_ids"],
            "concepts": refs["concepts"],
            "mechanisms": refs["mechanisms"],
            "variables_parameters": refs["variables_parameters"],
            "validation_status": validation,
            "draft_ready": draft_ready,
            "reviewer_comment": f"Risk of concept conflation: {risk}. Do not draft from unsupported or unpaged claims.",
        }
        rows.append(row)
    for section_num, title in MEMO_SECTIONS:
        parts.append(f"## {section_num}. {title}\n")
        for row in [r for r in rows if r["section"] == title]:
            parts.append(f"""### {row['paragraph_id']}

- Paragraph function: {row['paragraph_function']}
- Core claim: {row['core_claim']}
- Required evidence: {row['claim_ids'] or 'needs_claim_link'}
- Source IDs: {row['source_ids'] or 'needs_source_mapping'}
- Note IDs: {row['note_ids'] or 'needs_note_mapping'}
- Extraction claim IDs: {row['claim_ids'] or 'needs_claim_link'}
- Concepts used: {row['concepts'] or 'needs_concept_mapping'}
- Mechanisms used: {row['mechanisms'] or 'needs_mechanism_mapping'}
- Variables/parameters used: {row['variables_parameters'] or 'needs_variable_mapping'}
- Validation status: {row['validation_status']}
- Risk of concept conflation: {row['reviewer_comment']}
- Ready to draft: {row['draft_ready']}
""")
    write_text(outline_path, "\n".join(parts))
    write_csv(csv_path, rows, ["paragraph_id", "section", "paragraph_function", "core_claim", "source_ids", "note_ids", "claim_ids", "concepts", "mechanisms", "variables_parameters", "validation_status", "draft_ready", "reviewer_comment"])


def build_integrity_report(path: Path, registry: dict[str, Any], q_dir: Path, c_dir: Path, notes: list[str]) -> None:
    q_files = sorted(q_dir.glob("PDF*_Q*.md"))
    c_files = sorted(c_dir.glob("C*_Q*.md"))
    q_missing = [q["question_id"] for q in registry["questions"] if not (q_dir / f"{q['question_id']}.md").exists()]
    c_missing = [cq["cluster_question_id"] for cq in registry["cluster_questions"] if not (c_dir / f"{cq['cluster_question_id']}.md").exists()]
    no_note_marker = []
    for path_ in q_files:
        if "[NOTEBOOKLM]" not in path_.read_text(encoding="utf-8"):
            no_note_marker.append(path_.stem)
    for path_ in c_files:
        if "[NOTEBOOKLM_CLUSTER]" not in path_.read_text(encoding="utf-8"):
            no_note_marker.append(path_.stem)
    text = f"""# Note Integrity Report

Generated: {TODAY}

## Path Reconciliation

{chr(10).join(f'- {item}' for item in notes)}

Earlier reports and deleted tracked entries reference `notes/questions`. The live Phase 1 and Phase 2 note base is under `03_notes`.

## Counts

- Registry per-paper questions: {len(registry['questions'])}
- Per-paper notes found: {len(q_files)}
- Registry cluster questions: {len(registry['cluster_questions'])}
- Cluster notes found: {len(c_files)}

## Missing Notes

- Missing per-paper notes: {', '.join(q_missing) if q_missing else 'None'}
- Missing cluster notes: {', '.join(c_missing) if c_missing else 'None'}

## NotebookLM Markers

- Notes missing expected marker: {', '.join(no_note_marker) if no_note_marker else 'None'}

## Phase Boundary

Phase 3A did not overwrite Phase 1 or Phase 2 notes and did not fetch new NotebookLM answers.
"""
    write_text(path, text)


def build_execution_report(path: Path, files: list[Path], claims: list[dict[str, str]], q_count: int, c_count: int, validation_summary: str) -> None:
    dim_counts = Counter(c["dimension"] for c in claims)
    val_counts = Counter(c["validation_status"] for c in claims)
    text = f"""# Phase 3A Execution Report

Generated: {TODAY}

## Skills Inspected

- `05_skills/codex_prompt_bootstrap.md`
- `05_skills/SKILL_SYSTEMATIC_REVIEW_LANDRENT.md`
- `05_skills/SYSTEMATIC_REVIEW_ORCHESTRATOR.md`
- `05_skills/review_matrix_schema.csv`

## Unified Skill Synthesis

The new Phase 3 skill uses the orchestrator as governing protocol, the systematic review skill as operational checklist, and the CSV schema as extraction contract. The bootstrap file is treated as legacy first-pass infrastructure only.

## Note Counts

- Phase 1 per-paper notes: {q_count}
- Phase 2 cluster notes: {c_count}

## Extracted Claims

- Total claims: {len(claims)}
- Claims by dimension: {dict(dim_counts)}
- Claims by validation status: {dict(val_counts)}

## Concepts and Mechanisms

- Mandatory concepts populated: {len(MANDATORY_CONCEPTS)}
- Mandatory mechanisms populated: {len(MANDATORY_MECHANISMS)}
- Synthesis clusters populated: {len(THEMES)}

## Memo Architecture

- Paragraph slots: {len(paragraph_blueprint())}

## Files Created or Updated

{chr(10).join(f'- `{rel(path)}`' for path in files)}

## Validation Result

{validation_summary}

## Unresolved Issues

- Claims marked `needs_page` require exact page verification before final memo prose.
- C6 must remain marked as corpus-level all-source inference in Phase 3B.
- Secret-pattern findings, if any, are reported without values in the validation report and should be rotated if they are real credentials.

## Recommended Phase 3B

Draft the 5-15 page working memo from `04_review_artifacts/04_memo_architecture/paragraph_function_map.csv` and `04_review_artifacts/02_extraction/extraction_matrix.csv`, using only supported claims and preserving the controlled reconstruction-before-critique sequence.
"""
    write_text(path, text)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--registry", default="02_LitRev_Sistematica/config/registry_parsed.json")
    parser.add_argument("--evidence-map", default="02_LitRev_Sistematica/derived/cluster_evidence_map.json")
    parser.add_argument("--output-root", default="04_review_artifacts")
    args = parser.parse_args()

    registry_path = ROOT / args.registry
    registry = load_json(registry_path)
    q_dir, c_dir, path_notes = resolve_note_dirs()
    out_root = ROOT / args.output_root
    paths = {
        "skill": ROOT / "05_skills/SKILL_PHASE3_LANDRENT_SYNTHESIS.md",
        "protocol": out_root / "00_protocol/phase3_synthesis_protocol.md",
        "source_registry": out_root / "01_registries/source_registry.csv",
        "question_registry": out_root / "01_registries/question_registry.csv",
        "cluster_question_registry": out_root / "01_registries/cluster_question_registry.csv",
        "note_integrity": out_root / "01_registries/note_integrity_report.md",
        "extraction": out_root / "02_extraction/extraction_matrix.csv",
        "concepts": out_root / "02_extraction/concept_dictionary.md",
        "mechanisms": out_root / "02_extraction/mechanism_ledger.md",
        "variables": out_root / "02_extraction/variable_parameter_ledger.md",
        "theme_map": out_root / "03_synthesis/thematic_synthesis_map.md",
        "claim_cluster": out_root / "03_synthesis/claim_cluster_table.csv",
        "gap_memo": out_root / "03_synthesis/gap_and_transportability_memo.md",
        "outline": out_root / "04_memo_architecture/detailed_memo_outline.md",
        "paragraph_map": out_root / "04_memo_architecture/paragraph_function_map.csv",
        "execution_report": out_root / f"05_reports/phase3a_execution_report_{TODAY}.md",
    }
    for sub in ["00_protocol", "01_registries", "02_extraction", "03_synthesis", "04_memo_architecture", "05_reports"]:
        (out_root / sub).mkdir(parents=True, exist_ok=True)

    build_skill(paths["skill"])
    build_protocol(paths["protocol"], q_dir, c_dir)

    source_rows, question_rows, cluster_question_rows = registry_rows(registry, q_dir, c_dir)
    write_csv(paths["source_registry"], source_rows, list(source_rows[0].keys()))
    write_csv(paths["question_registry"], question_rows, list(question_rows[0].keys()))
    write_csv(paths["cluster_question_registry"], cluster_question_rows, list(cluster_question_rows[0].keys()))
    build_integrity_report(paths["note_integrity"], registry, q_dir, c_dir, path_notes)

    papers_by_id = {p["source_id"]: p for p in registry["papers"]}
    claims = build_question_claims(q_dir, registry, papers_by_id) + build_cluster_claims(c_dir, registry, papers_by_id)
    claims.sort(key=lambda row: row["claim_id"])
    write_csv(paths["extraction"], claims, EXTRACTION_COLUMNS)
    build_concept_dictionary(paths["concepts"], claims)
    build_mechanism_ledger(paths["mechanisms"], claims)
    build_variable_ledger(paths["variables"], claims)
    build_thematic_map(paths["theme_map"], claims)
    build_claim_cluster_table(paths["claim_cluster"], claims)
    build_gap_memo(paths["gap_memo"], claims)
    build_paragraph_artifacts(paths["outline"], paths["paragraph_map"], claims)

    validation_summary = "Run `python scripts/validate_phase3a_synthesis.py` for full validation."
    build_execution_report(paths["execution_report"], list(paths.values()), claims, len(list(q_dir.glob("PDF*_Q*.md"))), len(list(c_dir.glob("C*_Q*.md"))), validation_summary)

    print(f"Phase 3A artifacts generated under {rel(out_root)}")
    print(f"Claims extracted: {len(claims)}")
    print(f"Per-paper notes: {len(list(q_dir.glob('PDF*_Q*.md')))}")
    print(f"Cluster notes: {len(list(c_dir.glob('C*_Q*.md')))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
